<?php

class CF_Geoplugin_Data
{
	protected $region_country_list = array(
		"Australia and New Zealand" => array(
			"AU" => "Australia",
			"NZ" => "New Zealand",
			"NF" => "Norfolk Island",
		),
		"Caribbean" => array(
			"AI" => "Anguilla",
			"AG" => "Antigua and Barbuda",
			"AW" => "Aruba",
			"BS" => "Bahamas",
			"BB" => "Barbados",
			"VG" => "British Virgin Islands",
			"KY" => "Cayman Islands",
			"CU" => "Cuba",
			"DM" => "Dominica",
			"DO" => "Dominican Republic",
			"GD" => "Grenada",
			"GP" => "Guadeloupe",
			"HT" => "Haiti",
			"JM" => "Jamaica",
			"MQ" => "Martinique",
			"MS" => "Montserrat",
			"AN" => "Netherlands Antilles",
			"PR" => "Puerto Rico",
			"BL" => "Saint Barthélemy",
			"KN" => "Saint Kitts and Nevis",
			"LC" => "Saint Lucia",
			"MF" => "Saint Martin",
			"VC" => "Saint Vincent and the Grenadines",
			"TT" => "Trinidad and Tobago",
			"TC" => "Turks and Caicos Islands",
			"VI" => "U.S. Virgin Islands",
		),
		"Central America" => array(
			"BZ" => "Belize",
			"CR" => "Costa Rica",
			"SV" => "El Salvador",
			"GT" => "Guatemala",
			"HN" => "Honduras",
			"MX" => "Mexico",
			"NI" => "Nicaragua",
			"PA" => "Panama",
		),
		"Central Asia" => array(
			"KZ" => "Kazakhstan",
			"KG" => "Kyrgyzstan",
			"TJ" => "Tajikistan",
			"TM" => "Turkmenistan",
			"UZ" => "Uzbekistan",
		),
		"Channel Islands" => array(
			"GG" => "Guernsey",
			"JE" => "Jersey",
		),
		"Commonwealth of Independent States" => array(
			"AM" => "Armenia",
			"AZ" => "Azerbaijan",
			"BY" => "Belarus",
			"GE" => "Georgia",
			"KZ" => "Kazakhstan",
			"KG" => "Kyrgyzstan",
			"MD" => "Moldova",
			"RU" => "Russia",
			"TJ" => "Tajikistan",
			"TM" => "Turkmenistan",
			"UA" => "Ukraine",
			"UZ" => "Uzbekistan",
		),
		"Eastern Africa" => array(
			"BI" => "Burundi",
			"KM" => "Comoros",
			"DJ" => "Djibouti",
			"ER" => "Eritrea",
			"ET" => "Ethiopia",
			"KE" => "Kenya",
			"MG" => "Madagascar",
			"MW" => "Malawi",
			"MU" => "Mauritius",
			"YT" => "Mayotte",
			"MZ" => "Mozambique",
			"RW" => "Rwanda",
			"RE" => "Réunion",
			"SC" => "Seychelles",
			"SO" => "Somalia",
			"TZ" => "Tanzania",
			"UG" => "Uganda",
			"ZM" => "Zambia",
			"ZW" => "Zimbabwe",
		),
		"Eastern Asia" => array(
			"CN" => "China",
			"HK" => "Hong Kong SAR China",
			"JP" => "Japan",
			"MO" => "Macau SAR China",
			"MN" => "Mongolia",
			"KP" => "North Korea",
			"KR" => "South Korea",
			"TW" => "Taiwan",
		),
		"Eastern Europe" => array(
			"BY" => "Belarus",
			"BG" => "Bulgaria",
			"CZ" => "Czech Republic",
			"HU" => "Hungary",
			"MD" => "Moldova",
			"PL" => "Poland",
			"RO" => "Romania",
			"RU" => "Russia",
			"SK" => "Slovakia",
			"UA" => "Ukraine",
			"SU" => "Union of Soviet Socialist Republics",
		),
		"Melanesia" => array(
			"FJ" => "Fiji",
			"NC" => "New Caledonia",
			"PG" => "Papua New Guinea",
			"SB" => "Solomon Islands",
			"VU" => "Vanuatu",
		),
		"Micronesian Region" => array(
			"GU" => "Guam",
			"KI" => "Kiribati",
			"MH" => "Marshall Islands",
			"FM" => "Micronesia",
			"NR" => "Nauru",
			"MP" => "Northern Mariana Islands",
			"PW" => "Palau",
		),
		"Middle Africa" => array(
			"AO" => "Angola",
			"CM" => "Cameroon",
			"CF" => "Central African Republic",
			"TD" => "Chad",
			"CG" => "Congo - Brazzaville",
			"CD" => "Congo - Kinshasa",
			"GQ" => "Equatorial Guinea",
			"GA" => "Gabon",
			"ST" => "São Tomé and Príncipe",
		),
		"Northern Africa" => array(
			"DZ" => "Algeria",
			"EG" => "Egypt",
			"LY" => "Libya",
			"MA" => "Morocco",
			"SD" => "Sudan",
			"TN" => "Tunisia",
			"EH" => "Western Sahara",
		),
		"Northern America" => array(
			"BM" => "Bermuda",
			"CA" => "Canada",
			"GL" => "Greenland",
			"PM" => "Saint Pierre and Miquelon",
			"US" => "United States",
		),
		"Northern Europe" => array(
			"DK" => "Denmark",
			"EE" => "Estonia",
			"FO" => "Faroe Islands",
			"FI" => "Finland",
			"GG" => "Guernsey",
			"IS" => "Iceland",
			"IE" => "Ireland",
			"IM" => "Isle of Man",
			"JE" => "Jersey",
			"LV" => "Latvia",
			"LT" => "Lithuania",
			"NO" => "Norway",
			"SJ" => "Svalbard and Jan Mayen",
			"SE" => "Sweden",
			"GB" => "Great Britain",
			"AX" => "Åland Islands",
		),
		"Polynesia" => array(
			"AS" => "American Samoa",
			"CK" => "Cook Islands",
			"PF" => "French Polynesia",
			"NU" => "Niue",
			"PN" => "Pitcairn Islands",
			"WS" => "Samoa",
			"TK" => "Tokelau",
			"TO" => "Tonga",
			"TV" => "Tuvalu",
			"WF" => "Wallis and Futuna",
		),
		"South America" => array(
			"AR" => "Argentina",
			"BO" => "Bolivia",
			"BR" => "Brazil",
			"CL" => "Chile",
			"CO" => "Colombia",
			"EC" => "Ecuador",
			"FK" => "Falkland Islands",
			"GF" => "French Guiana",
			"GY" => "Guyana",
			"PY" => "Paraguay",
			"PE" => "Peru",
			"SR" => "Suriname",
			"UY" => "Uruguay",
			"VE" => "Venezuela",
		),
		"South-Eastern Asia" => array(
			"BN" => "Brunei",
			"KH" => "Cambodia",
			"ID" => "Indonesia",
			"LA" => "Laos",
			"MY" => "Malaysia",
			"MM" => "Myanmar [Burma]",
			"PH" => "Philippines",
			"SG" => "Singapore",
			"TH" => "Thailand",
			"TL" => "Timor-Leste",
			"VN" => "Vietnam",
		),
		"Southern Africa" => array(
			"BW" => "Botswana",
			"LS" => "Lesotho",
			"NA" => "Namibia",
			"ZA" => "South Africa",
			"SZ" => "Swaziland",
		),
		"Southern Asia" => array(
			"AF" => "Afghanistan",
			"BD" => "Bangladesh",
			"BT" => "Bhutan",
			"IN" => "India",
			"IR" => "Iran",
			"MV" => "Maldives",
			"NP" => "Nepal",
			"PK" => "Pakistan",
			"LK" => "Sri Lanka",
		),
		"Southern Europe" => array(
			"AL" => "Albania",
			"AD" => "Andorra",
			"BA" => "Bosnia and Herzegovina",
			"HR" => "Croatia",
			"GI" => "Gibraltar",
			"GR" => "Greece",
			"IT" => "Italy",
			"MK" => "Macedonia",
			"MT" => "Malta",
			"ME" => "Montenegro",
			"PT" => "Portugal",
			"SM" => "San Marino",
			"RS" => "Serbia",
			"CS" => "Serbia and Montenegro",
			"SI" => "Slovenia",
			"ES" => "Spain",
			"VA" => "Vatican City",
		),
		"Western Africa" => array(
			"BJ" => "Benin",
			"BF" => "Burkina Faso",
			"CV" => "Cape Verde",
			"CI" => "Côte d’Ivoire",
			"GM" => "Gambia",
			"GH" => "Ghana",
			"GN" => "Guinea",
			"GW" => "Guinea-Bissau",
			"LR" => "Liberia",
			"ML" => "Mali",
			"MR" => "Mauritania",
			"NE" => "Niger",
			"NG" => "Nigeria",
			"SH" => "Saint Helena",
			"SN" => "Senegal",
			"SL" => "Sierra Leone",
			"TG" => "Togo",
		),
		"Western Asia" => array(
			"AM" => "Armenia",
			"AZ" => "Azerbaijan",
			"BH" => "Bahrain",
			"CY" => "Cyprus",
			"GE" => "Georgia",
			"IQ" => "Iraq",
			"IL" => "Israel",
			"JO" => "Jordan",
			"KW" => "Kuwait",
			"LB" => "Lebanon",
			"NT" => "Neutral Zone",
			"OM" => "Oman",
			"PS" => "Palestinian Territories",
			"YD" => "People's Democratic Republic of Yemen",
			"QA" => "Qatar",
			"SA" => "Saudi Arabia",
			"SY" => "Syria",
			"TR" => "Turkey",
			"AE" => "United Arab Emirates",
			"YE" => "Yemen",
		),
		"Western Europe" => array(
			"AT" => "Austria",
			"BE" => "Belgium",
			"DD" => "East Germany",
			"FR" => "France",
			"DE" => "Germany",
			"LI" => "Liechtenstein",
			"LU" => "Luxembourg",
			"FX" => "Metropolitan France",
			"MC" => "Monaco",
			"NL" => "Netherlands",
			"CH" => "Switzerland",
		),
	);

	protected $region_list = array(
		"001" => "World",
		"002" => "Africa",
		"003" => "North America",
		"005" => "South America",
		"009" => "Oceania",
		"011" => "Western Africa",
		"013" => "Central America",
		"014" => "Eastern Africa",
		"015" => "Northern Africa",
		"017" => "Middle Africa",
		"018" => "Southern Africa",
		"019" => "Americas",
		"021" => "Northern America",
		"029" => "Caribbean",
		"030" => "Eastern Asia",
		"034" => "Southern Asia",
		"035" => "South-Eastern Asia",
		"039" => "Southern Europe",
		"053" => "Australia and New Zealand",
		"054" => "Melanesia",
		"057" => "Micronesian Region",
		"061" => "Polynesia",
		"062" => "South-Central Asia",
		"QO" => "Outlying Oceania",
		"QU" => "European Union",
		"142" => "Asia",
		"143" => "Central Asia",
		"145" => "Western Asia",
		"150" => "Europe",
		"151" => "Eastern Europe",
		"154" => "Northern Europe",
		"155" => "Western Europe",
		"172" => "Commonwealth of Independent States",
		"200" => "Czechoslovakia",
		"419" => "Latin America and the Caribbean",
		"830" => "Channel Islands",
	);
	
	protected $country_list = array(
		"AF" => "Afghanistan",
		"AL" => "Albania",
		"DZ" => "Algeria",
		"AS" => "American Samoa",
		"AD" => "Andorra",
		"AO" => "Angola",
		"AI" => "Anguilla",
		"AQ" => "Antarctica",
		"AG" => "Antigua and Barbuda",
		"AR" => "Argentina",
		"AM" => "Armenia",
		"AW" => "Aruba",
		"AU" => "Australia",
		"AT" => "Austria",
		"AZ" => "Azerbaijan",
		"BS" => "Bahamas",
		"BH" => "Bahrain",
		"BD" => "Bangladesh",
		"BB" => "Barbados",
		"BY" => "Belarus",
		"BE" => "Belgium",
		"BZ" => "Belize",
		"BJ" => "Benin",
		"BM" => "Bermuda",
		"BT" => "Bhutan",
		"BO" => "Bolivia",
		"BA" => "Bosnia and Herzegovina",
		"BW" => "Botswana",
		"BV" => "Bouvet Island",
		"BR" => "Brazil",
		"BQ" => "British Antarctic Territory",
		"IO" => "British Indian Ocean Territory",
		"VG" => "British Virgin Islands",
		"BN" => "Brunei",
		"BG" => "Bulgaria",
		"BF" => "Burkina Faso",
		"BI" => "Burundi",
		"KH" => "Cambodia",
		"CM" => "Cameroon",
		"CA" => "Canada",
		"CT" => "Canton and Enderbury Islands",
		"CV" => "Cape Verde",
		"KY" => "Cayman Islands",
		"CF" => "Central African Republic",
		"TD" => "Chad",
		"CL" => "Chile",
		"CN" => "China",
		"CX" => "Christmas Island",
		"CC" => "Cocos [Keeling] Islands",
		"CO" => "Colombia",
		"KM" => "Comoros",
		"CG" => "Congo - Brazzaville",
		"CD" => "Congo - Kinshasa",
		"CK" => "Cook Islands",
		"CR" => "Costa Rica",
		"HR" => "Croatia",
		"CU" => "Cuba",
		"CY" => "Cyprus",
		"CZ" => "Czech Republic",
		"CI" => "Côte d’Ivoire",
		"DK" => "Denmark",
		"DJ" => "Djibouti",
		"DM" => "Dominica",
		"DO" => "Dominican Republic",
		"NQ" => "Dronning Maud Land",
		"DD" => "East Germany",
		"EC" => "Ecuador",
		"EG" => "Egypt",
		"SV" => "El Salvador",
		"GQ" => "Equatorial Guinea",
		"ER" => "Eritrea",
		"EE" => "Estonia",
		"ET" => "Ethiopia",
		"FK" => "Falkland Islands",
		"FO" => "Faroe Islands",
		"FJ" => "Fiji",
		"FI" => "Finland",
		"FR" => "France",
		"GF" => "French Guiana",
		"PF" => "French Polynesia",
		"TF" => "French Southern Territories",
		"FQ" => "French Southern and Antarctic Territories",
		"GA" => "Gabon",
		"GM" => "Gambia",
		"GE" => "Georgia",
		"DE" => "Germany",
		"GH" => "Ghana",
		"GI" => "Gibraltar",
		"GR" => "Greece",
		"GL" => "Greenland",
		"GD" => "Grenada",
		"GP" => "Guadeloupe",
		"GU" => "Guam",
		"GT" => "Guatemala",
		"GG" => "Guernsey",
		"GN" => "Guinea",
		"GW" => "Guinea-Bissau",
		"GY" => "Guyana",
		"HT" => "Haiti",
		"HM" => "Heard Island and McDonald Islands",
		"HN" => "Honduras",
		"HK" => "Hong Kong SAR China",
		"HU" => "Hungary",
		"IS" => "Iceland",
		"IN" => "India",
		"ID" => "Indonesia",
		"IR" => "Iran",
		"IQ" => "Iraq",
		"IE" => "Ireland",
		"IM" => "Isle of Man",
		"IL" => "Israel",
		"IT" => "Italy",
		"JM" => "Jamaica",
		"JP" => "Japan",
		"JE" => "Jersey",
		"JT" => "Johnston Island",
		"JO" => "Jordan",
		"KZ" => "Kazakhstan",
		"KE" => "Kenya",
		"KI" => "Kiribati",
		"KW" => "Kuwait",
		"KG" => "Kyrgyzstan",
		"LA" => "Laos",
		"LV" => "Latvia",
		"LB" => "Lebanon",
		"LS" => "Lesotho",
		"LR" => "Liberia",
		"LY" => "Libya",
		"LI" => "Liechtenstein",
		"LT" => "Lithuania",
		"LU" => "Luxembourg",
		"MO" => "Macau SAR China",
		"MK" => "Macedonia",
		"MG" => "Madagascar",
		"MW" => "Malawi",
		"MY" => "Malaysia",
		"MV" => "Maldives",
		"ML" => "Mali",
		"MT" => "Malta",
		"MH" => "Marshall Islands",
		"MQ" => "Martinique",
		"MR" => "Mauritania",
		"MU" => "Mauritius",
		"YT" => "Mayotte",
		"FX" => "Metropolitan France",
		"MX" => "Mexico",
		"FM" => "Micronesia",
		"MI" => "Midway Islands",
		"MD" => "Moldova",
		"MC" => "Monaco",
		"MN" => "Mongolia",
		"ME" => "Montenegro",
		"MS" => "Montserrat",
		"MA" => "Morocco",
		"MZ" => "Mozambique",
		"MM" => "Myanmar [Burma]",
		"NA" => "Namibia",
		"NR" => "Nauru",
		"NP" => "Nepal",
		"NL" => "Netherlands",
		"AN" => "Netherlands Antilles",
		"NT" => "Neutral Zone",
		"NC" => "New Caledonia",
		"NZ" => "New Zealand",
		"NI" => "Nicaragua",
		"NE" => "Niger",
		"NG" => "Nigeria",
		"NU" => "Niue",
		"NF" => "Norfolk Island",
		"KP" => "North Korea",
		"VD" => "North Vietnam",
		"MP" => "Northern Mariana Islands",
		"NO" => "Norway",
		"OM" => "Oman",
		"PC" => "Pacific Islands Trust Territory",
		"PK" => "Pakistan",
		"PW" => "Palau",
		"PS" => "Palestinian Territories",
		"PA" => "Panama",
		"PZ" => "Panama Canal Zone",
		"PG" => "Papua New Guinea",
		"PY" => "Paraguay",
		"YD" => "People's Democratic Republic of Yemen",
		"PE" => "Peru",
		"PH" => "Philippines",
		"PN" => "Pitcairn Islands",
		"PL" => "Poland",
		"PT" => "Portugal",
		"PR" => "Puerto Rico",
		"QA" => "Qatar",
		"RO" => "Romania",
		"RU" => "Russia",
		"RW" => "Rwanda",
		"RE" => "Réunion",
		"BL" => "Saint Barthélemy",
		"SH" => "Saint Helena",
		"KN" => "Saint Kitts and Nevis",
		"LC" => "Saint Lucia",
		"MF" => "Saint Martin",
		"PM" => "Saint Pierre and Miquelon",
		"VC" => "Saint Vincent and the Grenadines",
		"WS" => "Samoa",
		"SM" => "San Marino",
		"SA" => "Saudi Arabia",
		"SN" => "Senegal",
		"RS" => "Serbia",
		"CS" => "Serbia and Montenegro",
		"SC" => "Seychelles",
		"SL" => "Sierra Leone",
		"SG" => "Singapore",
		"SK" => "Slovakia",
		"SI" => "Slovenia",
		"SB" => "Solomon Islands",
		"SO" => "Somalia",
		"ZA" => "South Africa",
		"GS" => "South Georgia and the South Sandwich Islands",
		"KR" => "South Korea",
		"ES" => "Spain",
		"LK" => "Sri Lanka",
		"SD" => "Sudan",
		"SR" => "Suriname",
		"SJ" => "Svalbard and Jan Mayen",
		"SZ" => "Swaziland",
		"SE" => "Sweden",
		"CH" => "Switzerland",
		"SY" => "Syria",
		"ST" => "São Tomé and Príncipe",
		"TW" => "Taiwan",
		"TJ" => "Tajikistan",
		"TZ" => "Tanzania",
		"TH" => "Thailand",
		"TL" => "Timor-Leste",
		"TG" => "Togo",
		"TK" => "Tokelau",
		"TO" => "Tonga",
		"TT" => "Trinidad and Tobago",
		"TN" => "Tunisia",
		"TR" => "Turkey",
		"TM" => "Turkmenistan",
		"TC" => "Turks and Caicos Islands",
		"TV" => "Tuvalu",
		"UM" => "U.S. Minor Outlying Islands",
		"PU" => "U.S. Miscellaneous Pacific Islands",
		"VI" => "U.S. Virgin Islands",
		"UG" => "Uganda",
		"UA" => "Ukraine",
		"SU" => "Union of Soviet Socialist Republics",
		"AE" => "United Arab Emirates",
		"GB" => "Great Britain",
		"US" => "United States",
	//	"ZZ" => "Unknown or Invalid Region",
		"UY" => "Uruguay",
		"UZ" => "Uzbekistan",
		"VU" => "Vanuatu",
		"VA" => "Vatican City",
		"VE" => "Venezuela",
		"VN" => "Vietnam",
		"WK" => "Wake Island",
		"WF" => "Wallis and Futuna",
		"EH" => "Western Sahara",
		"YE" => "Yemen",
		"ZM" => "Zambia",
		"ZW" => "Zimbabwe",
		"AX" => "Åland Islands",
	);

	private $taxonomy = false;

	function __construct($taxonomy=false){
		if($taxonomy!==false) $this->taxonomy=$taxonomy;
	}
	
	/**
	* Install into database
	*/
	public function install_country_terms($option=false, $taxonomy=false)
	{
		if($option!==false && in_array($option,array('region-country-list','region-list','country-list'))!==false)
		{
			// Set installation list
			$set=array(
				'region-country-list'	=>	$this->region_country_list,
				'region-list'			=>	$this->region_list,
				'country-list'		=>	$this->country_list,
			);
			// Set taxonomy or use global
			if($taxonomy!==false) $this->taxonomy=$taxonomy;
			
			$all_terms = cf_geo_get_terms(array(
				'taxonomy'		=> $this->taxonomy,
				'hide_empty'	=> false
			));

			if((is_array( $all_terms ) && count($all_terms)>0) || empty($this->taxonomy) || $this->taxonomy===false) {} else
			{
				$return = array();
				foreach($set[$option] as $region=>$array)
				{
					// Set Parent
					if(in_array($option,array('region_list','country_list'))!==false) $arg['description']	=	$array;
					
					if(is_string($array))
						$term	=	wp_insert_term( $region, $this->taxonomy, array('description' => $array) );
					else
						$term	=	wp_insert_term( $region, $this->taxonomy);
						
					$return[$region] =	$term;
					// Set Child
					if(is_array($array) && count($array)>0 && is_array($term))
					{
						foreach($array as $code=>$country)
						{
							$return[$country]	=	wp_insert_term(
								$country,
								$this->taxonomy,
								array(
									'parent'		=>	$term['term_id'],
									'description'	=>	$code
								)
							);
						}
					}
				}
				return $return;
			}
		}
		return false;
	}
}